version: '3.8'

services:
  
  client:
    image: react-go-app/client
    build: client
    stdin_open: true
    ports:
      - 3000:3000
    volumes:
      - ./client:/app
      - /app/node_modules

  server:
    image: react-go-app/sever
    build: server
    ports:
      - 8080:8080
    volumes:
      - ./server/src:/src
    environment:
      - MONGODB_URI=mongodb://db:27017/
      - PORT=8080

  db:
    image: mongo:4.2.6
    ports:
      - 27017:27017
      - 27018:27018
      - 27019:27019
    volumes:
      - ./scripts:/scripts
      - ./data/db:/data/db
  redis:
    image: redis:latest